[tool.poetry]
name = "utilpython"
version = "0.1.0"
description = ""
authors = ["fllovfgv <fllovfgv@gmail.com>"]
readme = "README.md"
packages = [
    { include = "app_genaiwk" },
]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
google-api-python-client = "^2.157.0"
bs4 = "^0.0.2"
google-cloud-aiplatform = "^1.75.0"
google-cloud-storage = "^2.19.0"
google-cloud-discoveryengine = "^0.13.5"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
