[tool.poetry]
name = "utilpython"
version = "0.1.0"
description = ""
authors = ["fllovfgv <fllovfgv@gmail.com>"]
readme = "README.md"
packages = [
    { include = "app_genaiwk" },
]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
google-cloud-discoveryengine = "^0.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
